// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6s9jiWq73TM9NBI3N_Mhy-u6zJJzonKs',
    appId: '1:515694934829:web:aa5a8dfdad3c630fdff1a4',
    messagingSenderId: '515694934829',
    projectId: 'orot-prp',
    authDomain: 'orot-prp.firebaseapp.com',
    storageBucket: 'orot-prp.firebasestorage.app',
    measurementId: 'G-FS11CB3TYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsNKYq3qzn6x3N70sQvfQu35tHFY7gqRE',
    appId: '1:515694934829:android:46976a1d454c183bdff1a4',
    messagingSenderId: '515694934829',
    projectId: 'orot-prp',
    storageBucket: 'orot-prp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUoQl2fDJQqhPg43nsO7d0cazpp2FKIZA',
    appId: '1:515694934829:ios:2c647c61a8fc6283dff1a4',
    messagingSenderId: '515694934829',
    projectId: 'orot-prp',
    storageBucket: 'orot-prp.firebasestorage.app',
    iosBundleId: 'com.example.orot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUoQl2fDJQqhPg43nsO7d0cazpp2FKIZA',
    appId: '1:515694934829:ios:2c647c61a8fc6283dff1a4',
    messagingSenderId: '515694934829',
    projectId: 'orot-prp',
    storageBucket: 'orot-prp.firebasestorage.app',
    iosBundleId: 'com.example.orot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6s9jiWq73TM9NBI3N_Mhy-u6zJJzonKs',
    appId: '1:515694934829:web:c5d40756986e85ecdff1a4',
    messagingSenderId: '515694934829',
    projectId: 'orot-prp',
    authDomain: 'orot-prp.firebaseapp.com',
    storageBucket: 'orot-prp.firebasestorage.app',
    measurementId: 'G-K27DEMHKPV',
  );
}
